'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Binoculars,Brain,Castle,ChevronUp,Flame,Hammer,Lock,Map,Plus,RefreshCcw,Shield,ShieldCheck,Skull,Sparkles,Swords,Trophy,Users,Wind,Zap} from 'lucide-react';
import {createGame3D} from './game3d';

type Owner='unknown'|'wild'|'enemy'|'own';
type Region={id:string;name:string;x:number;y:number;w:number;h:number;biome:string;color:string;owner:Owner;landmark:string};
type Mob={id:number;x:number;y:number;hp:number;max:number;name:string;tier:number;boss?:boolean;ally?:boolean;home:string;attackAnim?:number;attackTotal?:number;attackCd?:number;attackHit?:boolean;attackTarget?:number;hitAnim?:number;deathAnim?:number;dead?:boolean};
type Node={id:number;x:number;y:number;kind:'wood'|'ore';n:number};
type PendingHit={target:number;damage:number;delay:number;knockback?:number};
type StatKey='life'|'strength'|'defense'|'magic'|'agility'|'stamina'|'leadership';
type Stats=Record<StatKey,number>;
type JobSkill={id:string;name:string;desc:string;level:number;cost:number};
type Job={id:string;name:string;weapon:string;style:string;color:string;tier:'base'|'advanced';requires?:string[];power:number;magic:number;speed:number;range:number;minion:number;bonus:Partial<Stats>;skills:JobSkill[]};
type Career={lv:number;xp:number;skillPoints:number;stats:Stats;unlocked:string[];weaponLevel:number};
type World={x:number;y:number;hp:number;maxHp:number;xp:number;lv:number;rank:number;job:string;skillPoints:number;stats:Stats;unlocked:string[];weaponLevel:number;careers:Record<string,Career>;energy:number;maxEnergy:number;guarding:boolean;dodgeCd:number;dodgeTime:number;skillCd:number;heavyCd:number;attackAnim:number;attackTotal:number;attackKind:'none'|'normal'|'heavy'|'skill';hitAnim:number;buildAnim:number;pendingHits:PendingHit[];facingX:number;facingY:number;wood:number;ore:number;minions:number;base:number;lands:number;kills:number;bossKills:number;achievements:number;mobs:Mob[];nodes:Node[];discovered:string[];conquered:string[];message:string;banner:string;bannerTime:number;region:string;cd:number};
const RANKS=['F','E','D','C','B','A','S','魔王'];
const STAT_INFO:{id:StatKey;name:string;desc:string}[]=[
 {id:'life',name:'生命',desc:'最大HP +12'},{id:'strength',name:'力',desc:'物理攻撃力 +3'},{id:'defense',name:'耐久',desc:'被ダメージ軽減'},
 {id:'magic',name:'魔力',desc:'魔法・範囲威力'},{id:'agility',name:'敏捷',desc:'移動・攻撃速度'},{id:'stamina',name:'持久',desc:'自領での自然回復'},
 {id:'leadership',name:'統率',desc:'配下攻撃・勧誘力'}
];
const JOBS:Job[]=[
 {id:'blade',name:'魔剣士',weapon:'魔剣',style:'近接と魔法を切り替える万能型',color:'#a873ed',tier:'base',power:1.08,magic:.8,speed:1,range:1.05,minion:1,bonus:{strength:2,magic:2},skills:[{id:'flame-edge',name:'魔炎斬',desc:'攻撃に魔力を追加',level:1,cost:1},{id:'dark-wave',name:'闇の波動',desc:'攻撃範囲が拡大',level:3,cost:2},{id:'resonance',name:'魔剣共鳴',desc:'物理と魔法を相互強化',level:6,cost:3}]},
 {id:'berserker',name:'狂戦士',weapon:'大剣・戦斧',style:'一撃の威力を極めるパワー型',color:'#ef684f',tier:'base',power:1.38,magic:.1,speed:.82,range:1.15,minion:.8,bonus:{life:2,strength:4},skills:[{id:'rage',name:'血の狂乱',desc:'HP減少時に威力上昇',level:1,cost:1},{id:'crusher',name:'大地砕き',desc:'重撃で強敵へ追加威力',level:3,cost:2},{id:'undying',name:'不死の執念',desc:'致命傷を一度耐える',level:6,cost:3}]},
 {id:'mage',name:'魔術師',weapon:'魔杖',style:'遠距離と範囲魔法で制圧',color:'#6f8cff',tier:'base',power:.62,magic:1.65,speed:.92,range:1.75,minion:.9,bonus:{magic:5,stamina:1},skills:[{id:'bolt',name:'魔弾',desc:'遠距離攻撃を強化',level:1,cost:1},{id:'nova',name:'冥界ノヴァ',desc:'周囲の敵へ範囲ダメージ',level:3,cost:2},{id:'meteor',name:'魔星落とし',desc:'強敵へ大魔法を放つ',level:6,cost:3}]},
 {id:'shadow',name:'影魔',weapon:'双短剣',style:'高速移動と連撃で翻弄',color:'#5ee1cf',tier:'base',power:.88,magic:.35,speed:1.42,range:.85,minion:.9,bonus:{agility:5,strength:1},skills:[{id:'double',name:'影連斬',desc:'確率で二連続攻撃',level:1,cost:1},{id:'step',name:'虚影歩',desc:'移動速度をさらに強化',level:3,cost:2},{id:'assassin',name:'暗殺刻印',desc:'弱った敵へ大ダメージ',level:6,cost:3}]},
 {id:'lancer',name:'魔槍士',weapon:'長槍',style:'長い間合いと突進力を両立',color:'#e5b85c',tier:'base',power:1.12,magic:.25,speed:1.15,range:1.48,minion:1,bonus:{strength:2,agility:3},skills:[{id:'thrust',name:'魔槍突き',desc:'攻撃距離を延長',level:1,cost:1},{id:'charge',name:'黒風突進',desc:'移動中の威力上昇',level:3,cost:2},{id:'dragon',name:'竜穿槍',desc:'強敵の防御を貫通',level:6,cost:3}]},
 {id:'ruler',name:'支配者',weapon:'支配器',style:'配下の指揮と強化に特化',color:'#f093bd',tier:'base',power:.72,magic:.7,speed:.95,range:1.12,minion:2.2,bonus:{leadership:5,magic:1},skills:[{id:'command',name:'進軍命令',desc:'配下の攻撃力を強化',level:1,cost:1},{id:'dominate',name:'絶対服従',desc:'魔物を勧誘しやすくする',level:3,cost:2},{id:'legion',name:'魔王軍陣',desc:'配下数に応じて自身も強化',level:6,cost:3}]},
 {id:'warlock',name:'魔装覇王',weapon:'覇王魔装',style:'狂戦士の破壊力と支配者の軍勢を融合',color:'#ff835d',tier:'advanced',requires:['berserker','ruler'],power:1.55,magic:.7,speed:1.02,range:1.25,minion:1.8,bonus:{life:4,strength:5,leadership:3},skills:[{id:'tyrant',name:'暴君覚醒',desc:'自身と配下を同時強化',level:1,cost:2},{id:'warcry',name:'覇王号令',desc:'広範囲へ衝撃波を放つ',level:4,cost:3},{id:'overlord',name:'魔装解放',desc:'全能力を一時的に増幅',level:8,cost:4}]},
 {id:'nightseer',name:'冥影賢者',weapon:'影魔杖',style:'魔術師の範囲魔法と影魔の速度を融合',color:'#77a7ff',tier:'advanced',requires:['mage','shadow'],power:.95,magic:1.85,speed:1.35,range:1.85,minion:1,bonus:{magic:6,agility:5},skills:[{id:'blink',name:'冥界転移',desc:'回避距離と魔力を強化',level:1,cost:2},{id:'shade-nova',name:'影星ノヴァ',desc:'移動しながら範囲攻撃',level:4,cost:3},{id:'eclipse',name:'終夜蝕',desc:'広域を闇で制圧',level:8,cost:4}]},
 {id:'dragoon',name:'魔竜剣槍士',weapon:'魔竜剣槍',style:'魔剣と長槍を切り替える複合近接職',color:'#e6c36b',tier:'advanced',requires:['blade','lancer'],power:1.35,magic:.85,speed:1.22,range:1.55,minion:1,bonus:{strength:4,magic:3,agility:3},skills:[{id:'swap',name:'剣槍転式',desc:'間合いで武器を自動切替',level:1,cost:2},{id:'dragon-wave',name:'魔竜波',desc:'突進と魔法斬撃を連結',level:4,cost:3},{id:'dragon-soul',name:'竜魔魂',desc:'連撃ごとに威力上昇',level:8,cost:4}]}
];
type Milestone={level:number;skills:JobSkill[]};
const MILESTONE_NAMES:Record<string,string[]>={
 blade:['魔力装甲','吸魂剣','深紅の剣界','月蝕斬'],berserker:['粉砕衝動','血肉再生','巨神の一撃','絶命狂化'],
 mage:['連鎖魔弾','魔力障壁','虚無爆発','禁呪増幅'],shadow:['残影分身','毒刃刻印','無音暗殺','千影乱舞'],
 lancer:['旋回槍陣','雷光突き','天穿撃','竜騎疾走'],ruler:['軍勢鼓舞','魂の徴税','絶対指揮','王威結界'],
 warlock:['覇軍粉砕','暴君再生','魔王軍突撃','終焉魔装'],nightseer:['影魔障壁','転移魔弾','夜天崩落','無限残像'],
 dragoon:['剣槍連環','竜鱗守護','天魔穿孔','双極解放']
};
const milestonesFor=(jobId:string):Milestone[]=>{let names=MILESTONE_NAMES[jobId]||['覚醒攻撃','覚醒防御','奥義・破','奥義・守'];return[
 {level:4,skills:[{id:jobId+'-m4a',name:names[0],desc:'攻撃系統を伸ばす節目スキル',level:4,cost:2},{id:jobId+'-m4b',name:names[1],desc:'生存・補助系統を伸ばす節目スキル',level:4,cost:2}]},
 {level:8,skills:[{id:jobId+'-m8a',name:names[2],desc:'高威力の奥義系統へ進む',level:8,cost:3},{id:jobId+'-m8b',name:names[3],desc:'特殊戦術の奥義系統へ進む',level:8,cost:3}]}
]};
const REGIONS:Region[]=[
 {id:'ruins',name:'忘れられた廃墟',x:0,y:0,w:800,h:520,biome:'廃墟',color:'#353347',owner:'own',landmark:'小さな拠点'},
 {id:'forest',name:'囁きの魔樹海',x:800,y:0,w:800,h:520,biome:'森',color:'#163d38',owner:'wild',landmark:'魔族の集落'},
 {id:'mountain',name:'骸骨岩山',x:1600,y:0,w:800,h:520,biome:'岩山',color:'#403945',owner:'enemy',landmark:'白骨砦'},
 {id:'waste',name:'赤錆の荒野',x:0,y:520,w:800,h:520,biome:'荒野',color:'#563328',owner:'wild',landmark:'放棄された監視塔'},
 {id:'village',name:'薄暮の集落',x:800,y:520,w:800,h:520,biome:'魔族集落',color:'#3e2546',owner:'enemy',landmark:'角笛の市場'},
 {id:'fort',name:'黒曜領',x:1600,y:520,w:800,h:520,biome:'砦',color:'#44202b',owner:'enemy',landmark:'黒曜砦'},
 {id:'cave',name:'底無し洞窟',x:0,y:1040,w:800,h:520,biome:'洞窟',color:'#1b2637',owner:'enemy',landmark:'深淵の裂け目'},
 {id:'volcano',name:'業火火山',x:800,y:1040,w:800,h:520,biome:'火山',color:'#54221e',owner:'enemy',landmark:'灼熱祭壇'},
 {id:'castle',name:'魔王城外郭',x:1600,y:1040,w:800,h:520,biome:'城',color:'#281b3f',owner:'enemy',landmark:'封印された魔王城'}
];
const regionAt=(x:number,y:number)=>REGIONS.find(r=>x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h)||REGIONS[0];
const ownerOf=(w:World,r:Region):Owner=>w.conquered.includes(r.id)?'own':r.owner;
const jobOf=(w:World)=>JOBS.find(j=>j.id===w.job)||JOBS[0];
const d=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
const spawn=():Mob[]=>[
 [1,500,290,'はぐれインプ',1,'ruins'],[2,680,430,'灰角インプ',1,'ruins'],
 [3,980,230,'魔樹ゴブリン',1,'forest'],[4,1320,390,'毒牙ウルフ',2,'forest'],
 [5,1810,260,'岩鎧オーガ',3,'mountain'],[6,2160,410,'白骨騎士',3,'mountain'],
 [7,310,770,'砂塵ハウンド',2,'waste'],[8,640,930,'荒野の略奪者',2,'waste'],
 [9,1050,700,'槍持ち魔族',2,'village'],[10,1450,900,'集落の番人',3,'village'],
 [11,1800,720,'黒曜兵',3,'fort'],[12,2150,880,'黒曜守備隊長',4,'fort'],
 [13,350,1260,'洞窟スライム',2,'cave'],[14,680,1450,'深淵グール',3,'cave'],
 [15,1050,1250,'火炎サラマンダー',4,'volcano'],[16,1440,1450,'火口の巨人',5,'volcano'],
 [17,1850,1270,'魔城ガーゴイル',5,'castle'],[18,2200,1440,'封印の騎士',6,'castle']
 ].map(v=>{let t=v[4] as number,m=28+t*18;return{id:v[0] as number,x:v[1] as number,y:v[2] as number,name:v[3] as string,tier:t,hp:m,max:m,home:v[5] as string}});
const resources=():Node[]=>Array.from({length:27},(_,i)=>({id:i,x:150+(i*337)%2150,y:130+(i*211)%1320,kind:i%2?'wood':'ore',n:3+(i%3)}));
const baseStats=():Stats=>({life:1,strength:1,defense:1,magic:1,agility:1,stamina:1,leadership:1});
const fresh=():World=>({x:330,y:300,hp:100,maxHp:100,xp:0,lv:1,rank:0,job:'',skillPoints:0,stats:baseStats(),unlocked:[],weaponLevel:1,careers:{},energy:100,maxEnergy:100,guarding:false,dodgeCd:0,dodgeTime:0,skillCd:0,heavyCd:0,attackAnim:0,attackTotal:.62,attackKind:'none',hitAnim:0,buildAnim:0,pendingHits:[],facingX:1,facingY:0,wood:0,ore:0,minions:0,base:1,lands:1,kills:0,bossKills:0,achievements:0,mobs:spawn(),nodes:resources(),discovered:['ruins'],conquered:['ruins'],message:'職業を選び、魔王への一歩を踏み出せ。',banner:'自分の領土',bannerTime:2,region:'ruins',cd:0});
const requirement=(w:World)=>[
 '開始ランク',
 'Lv.2・敵撃破2・地域発見2',
 'Lv.3・配下1・実績1',
 'Lv.4・拠点Lv.2・敵撃破6',
 'Lv.5・領土2・配下2・強敵撃破1',
 'Lv.7・領土3・配下4・実績4',
 'Lv.9・領土5・強敵撃破3・実績6',
 'Lv.10以上・領土7・配下6・強敵撃破5・拠点Lv.5'
][Math.min(w.rank+1,7)];
const canRank=(w:World)=>{
 if(w.rank===0)return w.lv>=2&&w.kills>=2&&w.discovered.length>=2;
 if(w.rank===1)return w.lv>=3&&w.minions>=1&&w.achievements>=1;
 if(w.rank===2)return w.lv>=4&&w.base>=2&&w.kills>=6;
 if(w.rank===3)return w.lv>=5&&w.lands>=2&&w.minions>=2&&w.bossKills>=1;
 if(w.rank===4)return w.lv>=7&&w.lands>=3&&w.minions>=4&&w.achievements>=4;
 if(w.rank===5)return w.lv>=9&&w.lands>=5&&w.bossKills>=3&&w.achievements>=6;
 if(w.rank===6)return w.lv>=10&&w.lands>=7&&w.minions>=6&&w.bossKills>=5&&w.base>=5;
 return false;
};
const snapshotCareer=(w:World):Career=>({lv:w.lv,xp:w.xp,skillPoints:w.skillPoints,stats:{...w.stats},unlocked:[...w.unlocked],weaponLevel:w.weaponLevel});
const careerLevel=(w:World,id:string)=>w.job===id?w.lv:(w.careers[id]?.lv||0);
const jobUnlocked=(w:World,j:Job)=>j.tier==='base'||(j.requires||[]).every(id=>careerLevel(w,id)>=6);
const newCareer=(j:Job):Career=>{let stats=baseStats();Object.entries(j.bonus).forEach(([key,value])=>stats[key as StatKey]+=value||0);return{lv:1,xp:0,skillPoints:j.tier==='advanced'?3:1,stats,unlocked:[],weaponLevel:1}};
const applyCareer=(w:World,id:string,c:Career)=>{w.job=id;w.lv=c.lv;w.xp=c.xp;w.skillPoints=c.skillPoints;w.stats={...c.stats};w.unlocked=[...c.unlocked];w.weaponLevel=c.weaponLevel;w.maxHp=100+w.stats.life*12+(w.lv-1)*8+w.base*12;w.hp=w.maxHp;w.energy=w.maxEnergy};

export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),game=useRef(fresh()),keys=useRef<Record<string,boolean>>({}),stick=useRef({x:0,y:0,on:false}),[hud,setHud]=useState<World>(fresh),[mapOpen,setMapOpen]=useState(false),[rankOpen,setRankOpen]=useState(false),[growthOpen,setGrowthOpen]=useState(false),[transferOpen,setTransferOpen]=useState(false);
 const sync=useCallback(()=>setHud({...game.current,stats:{...game.current.stats},unlocked:[...game.current.unlocked],careers:{...game.current.careers},mobs:[...game.current.mobs],nodes:[...game.current.nodes],discovered:[...game.current.discovered],conquered:[...game.current.conquered]}),[]);
 const say=(s:string)=>{game.current.message=s;sync()};
 const chooseJob=(id:string)=>{let w=game.current,j=JOBS.find(x=>x.id===id);if(!j||j.tier!=='base')return;let career=newCareer(j);applyCareer(w,id,career);w.message=j.name+'として目覚めた。武器「'+j.weapon+'」を手にした！';sync()};
 const changeJob=(id:string)=>{let w=game.current,j=JOBS.find(x=>x.id===id);if(!j||id===w.job)return;if(!jobUnlocked(w,j))return say('必要職業をLv.6まで育成すると解放される。');let known=!!w.careers[id],cost=3+Object.keys(w.careers).length;if(!known&&(w.wood<cost||w.ore<cost))return say('新職への転職には魔木・瘴気鉱 各'+cost+'が必要。');if(w.job)w.careers[w.job]=snapshotCareer(w);if(!known){w.wood-=cost;w.ore-=cost}let career=w.careers[id]||newCareer(j);applyCareer(w,id,career);w.message=j.name+'へ転職。'+(known?'以前の職業進行を復元した。':'Lv.1・武器Lv.1から再修行が始まる。');setTransferOpen(false);sync()};
 const upgradeWeapon=()=>{let w=game.current,cost=w.weaponLevel+2;if(w.wood<cost||w.ore<cost)return say('武器強化には魔木・瘴気鉱 各'+cost+'が必要。');w.wood-=cost;w.ore-=cost;w.weaponLevel++;w.message=jobOf(w).weapon+'をLv.'+w.weaponLevel+'へ強化！';sync()};
 const gain=(n:number)=>{let w=game.current;if(w.lv>=99){w.xp=0;return}w.xp+=n;while(w.lv<99&&w.xp>=w.lv*34){w.xp-=w.lv*34;w.lv++;w.skillPoints+=3;w.maxHp+=8;w.hp=w.maxHp;w.achievements++;w.message=(w.lv===4||w.lv===8)?'Lv.'+w.lv+'の節目！ 二択スキルを無料で1つ選べる。':'Lv.'+w.lv+'！ スキルポイントを3獲得。'}if(w.lv>=99)w.xp=0};
 const queueHit=(w:World,t:Mob,damage:number,delay:number,knockback=0)=>w.pendingHits.push({target:t.id,damage,delay,knockback});
 const defeat=(w:World,t:Mob)=>{if(t.dead)return;t.dead=true;t.deathAnim=1.15;t.hitAnim=.32;w.kills++;if(t.boss){w.bossKills++;if(!w.conquered.includes(t.home)){w.conquered.push(t.home);w.lands++}w.achievements++;w.message=t.name+'を撃破！ '+regionAt(t.x,t.y).name+'を領土にした。'}else{w.ore++;gain(12+t.tier*5);w.message=t.name+'を撃破。瘴気鉱を獲得。'}};
 const attack=()=>{let w=game.current;if(!w.job)return say('先に職業を選択しよう。');if(w.cd>0||w.guarding)return;let j=jobOf(w),range=100*j.range*(w.unlocked.includes('dark-wave')||w.unlocked.includes('thrust')?1.18:1),targets=w.mobs.filter(m=>!m.ally&&!m.dead&&d(w,m)<range).sort((a,b)=>d(w,a)-d(w,b)),t=targets[0];if(!t)return say(j.weapon+'の攻撃範囲に敵がいない。');let branchPower=1+w.unlocked.filter(s=>s.endsWith('a')).length*.08,hit=Math.floor((12+w.lv*4+w.weaponLevel*4+w.stats.strength*3+w.stats.magic*4*j.magic+w.minions*j.minion*(2+w.stats.leadership*.3))*j.power*(1+w.unlocked.length*.04)*branchPower);if(w.job==='berserker'&&w.unlocked.includes('rage')&&w.hp<w.maxHp/2)hit=Math.floor(hit*1.35);if(w.job==='shadow'&&w.unlocked.includes('assassin')&&t.hp<t.max*.35)hit=Math.floor(hit*1.6);if(w.job==='ruler'&&w.unlocked.includes('legion'))hit+=w.minions*5;queueHit(w,t,hit,.29);if(w.job==='mage'&&w.unlocked.includes('nova'))targets.slice(1,4).forEach(m=>queueHit(w,m,Math.floor(hit*.35),.32));if(w.job==='shadow'&&w.unlocked.includes('double'))queueHit(w,t,Math.floor(hit*.35),.39);w.cd=.38/(j.speed*(1+w.stats.agility*.025));w.attackTotal=.62;w.attackAnim=w.attackTotal;w.attackKind='normal';w.message=j.name+'が構え、'+j.weapon+'で踏み込む！';sync()};
 const heavyAttack=()=>{let w=game.current;if(!w.job||w.heavyCd>0||w.energy<28||w.guarding)return;let j=jobOf(w),t=w.mobs.filter(m=>!m.ally&&!m.dead&&d(w,m)<125*j.range).sort((a,b)=>d(w,a)-d(w,b))[0];if(!t)return say('強攻撃の間合いに敵がいない。');let hit=Math.floor((20+w.lv*6+w.weaponLevel*7+w.stats.strength*5+w.stats.magic*3*j.magic)*j.power*1.65);if(w.unlocked.includes('crusher')&&t.boss)hit=Math.floor(hit*1.35);queueHit(w,t,hit,.51,35);w.energy-=28;w.heavyCd=1.1;w.attackTotal=.96;w.attackAnim=w.attackTotal;w.attackKind='heavy';w.message='重心を落とし、渾身の一撃を振りかぶる！';sync()};
 const dodge=()=>{let w=game.current;if(!w.job||w.dodgeCd>0||w.energy<22)return;w.energy-=22;w.dodgeCd=.82;w.dodgeTime=.48;w.x=Math.max(30,Math.min(2370,w.x+w.facingX*95));w.y=Math.max(30,Math.min(1530,w.y+w.facingY*95));w.message='回避！ 身を沈めて攻撃をすり抜けた。';sync()};
 const useCombatSkill=()=>{let w=game.current;if(!w.job||w.skillCd>0||w.energy<35)return;let j=jobOf(w),targets=w.mobs.filter(m=>!m.ally&&!m.dead&&d(w,m)<155*j.range).slice(0,6);if(!targets.length)return say('スキルの範囲に敵がいない。');let hit=Math.floor((25+w.lv*5+w.weaponLevel*5+w.stats.magic*7+w.stats.strength*3)*(.7+j.magic*.55)),known=j.skills.find(s=>w.unlocked.includes(s.id));targets.forEach((t,i)=>queueHit(w,t,hit,.45+i*.025,12));w.energy-=35;w.skillCd=3.2;w.attackTotal=1.08;w.attackAnim=w.attackTotal;w.attackKind='skill';w.message=(known?.name||j.name+'固有技')+'の魔力を全身に集める！';sync()};
 const recruit=()=>{let w=game.current;if(!w.job)return say('先に職業を選択しよう。');let threshold=.48+w.stats.leadership*.012+(w.job==='ruler'?.12:0)+(w.unlocked.includes('dominate')?.12:0),t=w.mobs.find(m=>!m.ally&&!m.boss&&!m.dead&&m.hp/m.max<=threshold&&d(w,m)<110);if(!t)return say('敵を弱らせよう。現在の勧誘可能HP：'+Math.round(threshold*100)+'%以下。');t.ally=true;t.hp=t.max;t.attackAnim=0;t.attackCd=0;w.minions++;if(w.minions===1)w.achievements++;w.message=t.name+'が'+jobOf(w).name+'に服従した！';sync()};
 const allocate=(key:StatKey)=>{let w=game.current;if(w.skillPoints<1)return;w.skillPoints--;w.stats[key]++;if(key==='life'){w.maxHp+=12;w.hp+=12}w.message=STAT_INFO.find(s=>s.id===key)!.name+'を強化した。';sync()};
 const learn=(skill:JobSkill)=>{let w=game.current;if(w.unlocked.includes(skill.id))return;if(w.lv<skill.level)return say('習得にはLv.'+skill.level+'が必要。');if(w.skillPoints<skill.cost)return say('スキルポイントが'+skill.cost+'必要。');w.skillPoints-=skill.cost;w.unlocked.push(skill.id);w.message='職業スキル「'+skill.name+'」を習得！';sync()};
 const learnMilestone=(group:Milestone,skill:JobSkill)=>{let w=game.current;if(w.unlocked.includes(skill.id))return;if(w.lv<group.level)return say('節目の選択はLv.'+group.level+'で解放。');let already=group.skills.some(s=>w.unlocked.includes(s.id)),cost=already?skill.cost:0;if(w.skillPoints<cost)return say('選ばなかった節目スキルの追加習得には'+cost+' SP必要。');w.skillPoints-=cost;w.unlocked.push(skill.id);w.message=already?'節目スキル「'+skill.name+'」を追加習得！':'Lv.'+group.level+'の節目で「'+skill.name+'」を選択！';sync()};
 const gather=()=>{let w=game.current,n=w.nodes.find(n=>n.n&&d(w,n)<75);if(!n)return say('光る魔木・瘴気鉱の近くで採集できる。');n.n--;if(n.kind==='wood')w.wood++;else w.ore++;w.message=n.kind==='wood'?'魔木を採集した。':'瘴気鉱を採集した。';sync()};
 const build=()=>{let w=game.current,c=w.base+2;if(w.wood<c||w.ore<c)return say('拠点強化には魔木・瘴気鉱 各'+c+'が必要。');w.wood-=c;w.ore-=c;w.base++;w.maxHp+=12;w.hp=w.maxHp;w.achievements++;w.buildAnim=5.5;w.message='配下が建築開始！ 足場を組み、拠点Lv.'+w.base+'へ強化する。';sync()};
 const raid=()=>{let w=game.current,r=regionAt(w.x,w.y);if(ownerOf(w,r)!=='enemy')return say('敵領土のランドマーク付近で領土ボスを呼び出せる。');if(w.mobs.some(m=>m.boss&&!m.dead&&m.home===r.id))return say('この領土の支配者はすでに出現している。');let required=Math.max(2,REGIONS.indexOf(r)-1);if(w.lv<required)return say('この領土の瘴気は強すぎる。推奨Lv.'+required+'。');w.mobs.push({id:100+w.bossKills,x:r.x+r.w*.68,y:r.y+r.h*.5,hp:150+required*35,max:150+required*35,name:r.name+'の支配者',tier:required,boss:true,home:r.id,attackAnim:0,attackCd:.8});w.message='領土ボスが出現！ 倒せばこの地を奪える。';sync()};
 const rankUp=()=>{let w=game.current;if(w.rank>=7)return say('すでに魔王として君臨している。');if(!canRank(w))return say('昇格条件が不足している：'+requirement(w));w.rank++;w.maxHp+=25;w.hp=w.maxHp;w.achievements++;w.message=w.rank===7?'魔王戴冠！ レベルだけでは届かない覇道を成し遂げた。':'魔族ランク '+RANKS[w.rank]+' に昇格！';sync()};
 useEffect(()=>{let down=(e:KeyboardEvent)=>{let key=e.key.toLowerCase();keys.current[key]=true;if(e.key===' '){e.preventDefault();attack()}if(key==='q')heavyAttack();if(key==='e')recruit();if(key==='f')gather();if(key==='m')setMapOpen(v=>!v);if(key==='shift')dodge();if(key==='c')useCombatSkill();if(key==='r')game.current.guarding=true},up=(e:KeyboardEvent)=>{let key=e.key.toLowerCase();keys.current[key]=false;if(key==='r')game.current.guarding=false};addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const view=createGame3D(c,REGIONS);let last=performance.now(),frame=0,id=0;
  const loop=(now:number)=>{let dt=Math.min(.04,(now-last)/1000);last=now;frame++;let w=game.current,ax=(keys.current.d||keys.current.arrowright?1:0)-(keys.current.a||keys.current.arrowleft?1:0)+(stick.current.on?stick.current.x:0),ay=(keys.current.s||keys.current.arrowdown?1:0)-(keys.current.w||keys.current.arrowup?1:0)+(stick.current.on?stick.current.y:0),intent=Math.min(1,Math.hypot(ax,ay)),z=Math.hypot(ax,ay)||1,j=jobOf(w),move=w.job?190*j.speed*(1+w.stats.agility*.018)*(w.unlocked.includes('step')?1.15:1):0,actionSlow=w.attackAnim>0?(w.attackKind==='heavy'?.28:.48):w.guarding?.45:1;if(intent>.1){w.facingX=ax/z;w.facingY=ay/z}w.x=Math.max(30,Math.min(2370,w.x+ax/z*move*intent*dt*actionSlow));w.y=Math.max(30,Math.min(1530,w.y+ay/z*move*intent*dt*actionSlow));w.cd=Math.max(0,w.cd-dt);w.heavyCd=Math.max(0,w.heavyCd-dt);w.dodgeCd=Math.max(0,w.dodgeCd-dt);w.dodgeTime=Math.max(0,w.dodgeTime-dt);w.skillCd=Math.max(0,w.skillCd-dt);w.attackAnim=Math.max(0,w.attackAnim-dt);if(w.attackAnim<=0)w.attackKind='none';w.hitAnim=Math.max(0,w.hitAnim-dt);w.buildAnim=Math.max(0,w.buildAnim-dt);w.energy=Math.min(w.maxEnergy,w.energy+(12+w.stats.stamina*1.2)*dt);if(w.guarding){w.energy=Math.max(0,w.energy-8*dt);if(w.energy<=0)w.guarding=false}w.pendingHits.forEach(hit=>hit.delay-=dt);let impacts=w.pendingHits.filter(hit=>hit.delay<=0);w.pendingHits=w.pendingHits.filter(hit=>hit.delay>0);impacts.forEach(hit=>{let t=w.mobs.find(m=>m.id===hit.target);if(!t||t.dead)return;t.hp-=hit.damage;t.hitAnim=.34;if(hit.knockback){let q=d(w,t)||1;t.x+=(t.x-w.x)/q*hit.knockback;t.y+=(t.y-w.y)/q*hit.knockback}if(t.hp<=0)defeat(w,t)});w.bannerTime=Math.max(0,w.bannerTime-dt);let r=regionAt(w.x,w.y);if(r.id!==w.region){w.region=r.id;if(!w.discovered.includes(r.id)){w.discovered.push(r.id);w.achievements++;w.message='新地域発見：'+r.name}let territory=ownerOf(w,r);w.banner=territory==='enemy'?'敵領土':territory==='own'?'自分の領土':'未支配地域';w.bannerTime=2.4}if(frame%60===0&&ownerOf(w,r)==='own')w.hp=Math.min(w.maxHp,w.hp+Math.max(1,Math.floor(w.stats.stamina*.45)));
  w.mobs.forEach(m=>{m.attackCd=Math.max(0,(m.attackCd||0)-dt);m.hitAnim=Math.max(0,(m.hitAnim||0)-dt);if(m.dead){m.deathAnim=Math.max(0,(m.deathAnim||0)-dt);return}let q=d(w,m),target:Mob|undefined,reach=m.boss?62:48;if(m.ally){target=w.mobs.filter(x=>!x.ally&&!x.dead).sort((a,b)=>d(m,a)-d(m,b))[0];let tq=target?d(m,target):999;if(target&&tq<190){if(tq>reach&&!(m.attackAnim||0)){m.x+=(target.x-m.x)/tq*(88+w.stats.leadership*2)*dt;m.y+=(target.y-m.y)/tq*(88+w.stats.leadership*2)*dt}else if(tq<=reach&&(m.attackCd||0)<=0){m.attackTotal=.72;m.attackAnim=m.attackTotal;m.attackCd=1.15;m.attackHit=false;m.attackTarget=target.id}}else if(q>80&&!(m.attackAnim||0)){m.x+=(w.x-m.x)/q*(80+w.stats.leadership*2)*dt;m.y+=(w.y-m.y)/q*(80+w.stats.leadership*2)*dt}}else{if(q<220&&q>reach&&!(m.attackAnim||0)){m.x+=(w.x-m.x)/q*(m.boss?44:55)*dt;m.y+=(w.y-m.y)/q*(m.boss?44:55)*dt}else if(q<=reach&&(m.attackCd||0)<=0){m.attackTotal=m.boss?1.18:.78;m.attackAnim=m.attackTotal;m.attackCd=m.boss?1.75:1.2;m.attackHit=false}}if((m.attackAnim||0)>0){let progress=1-(m.attackAnim||0)/(m.attackTotal||.78);if(progress>.5&&!m.attackHit){m.attackHit=true;if(m.ally){let victim=w.mobs.find(x=>x.id===m.attackTarget&&!x.dead);if(victim&&d(m,victim)<reach+25){victim.hp-=Math.max(2,3+m.tier*2+Math.floor(w.stats.leadership*.8));victim.hitAnim=.3;if(victim.hp<=0)defeat(w,victim)}}else if(d(w,m)<reach+28&&w.dodgeTime<=0){let branchGuard=1-w.unlocked.filter(s=>s.endsWith('b')).length*.08,harm=Math.max(1,Math.floor(((m.boss?13:3+m.tier)-Math.floor(w.stats.defense*.55))*branchGuard));if(w.guarding){harm=Math.max(1,Math.floor(harm*.28));w.energy=Math.max(0,w.energy-10)}w.hp-=harm;w.hitAnim=.34}}m.attackAnim=Math.max(0,(m.attackAnim||0)-dt)}});w.mobs=w.mobs.filter(m=>!m.dead||(m.deathAnim||0)>0);if(w.hp<=0){if(w.job==='berserker'&&w.unlocked.includes('undying')){w.hp=1;w.unlocked=w.unlocked.filter(s=>s!=='undying');w.message='不死の執念で致命傷に耐えた！'}else{w.x=330;w.y=300;w.hp=w.maxHp;w.message='敗北。忘れられた廃墟へ撤退した。'}}view.render(w,dt);if(frame%10===0)sync();id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(id);view.dispose()}},[sync]);
  const current=regionAt(hud.x,hud.y),currentOwner=ownerOf(hud,current),need=hud.lv*34,ready=canRank(hud),currentJob=JOBS.find(j=>j.id===hud.job),milestoneGroups=currentJob?milestonesFor(currentJob.id):[];
 return <main className="game-shell"><section className="game-frame open-world">
  <header className="topbar"><div className="brand"><Flame size={20} fill="currentColor"/><span>魔界成り上がり譚</span><small>3D OPEN WORLD</small></div><div className={'zone-chip '+currentOwner}><Map size={14}/><span>{current.name}</span><b>{currentOwner==='enemy'?'敵領土':currentOwner==='own'?'自分の領土':'未支配地域'}</b></div><button className="reset" onClick={()=>{game.current=fresh();sync()}}>最初から</button></header>
  <div className="hud-left"><button className={'rank-badge rank-button '+(ready?'ready':'')} onClick={()=>setRankOpen(v=>!v)}><span>RANK</span><b>{RANKS[hud.rank]}</b>{ready&&<ChevronUp size={12}/>}</button><div className="vitals"><div className="lv">LV <b>{hud.lv}</b><em>{currentJob?currentJob.name:'未選択'}</em></div><div className="meter hp"><i style={{width:(hud.hp/hud.maxHp*100)+'%'}}/></div><div className="meter xp"><i style={{width:(hud.lv>=99?100:hud.xp/need*100)+'%'}}/></div><small>HP {Math.ceil(hud.hp)}/{hud.maxHp}　{hud.lv>=99?'LEVEL MAX':'EXP '+hud.xp+'/'+need}</small></div></div>
  <div className="hud-right"><div className={hud.skillPoints?'sp-ready':''}><Brain size={15}/>SP <b>{hud.skillPoints}</b></div><div><Users size={15}/>配下 <b>{hud.minions}</b></div><div><Castle size={15}/>領土 <b>{hud.lands}</b></div><div><Trophy size={15}/>実績 <b>{hud.achievements}</b></div></div>
  <canvas ref={canvas} className="game-canvas" aria-label="リアルタイム3D魔界フィールド"/>
  {!hud.job&&<div className="job-select"><div className="job-title"><span>GAME START</span><h1>最初の職業を選べ</h1><p>職業は武器・間合い・成長方針・専用スキルを大きく変えます</p></div><div className="job-grid">{JOBS.filter(j=>j.tier==='base').map(j=><button key={j.id} className={'job-card '+j.id} onClick={()=>chooseJob(j.id)} style={{'--job-color':j.color} as React.CSSProperties}><div className="job-mark"><Swords/></div><span>{j.weapon}</span><h2>{j.name}</h2><p>{j.style}</p><div className="job-bars"><i style={{width:(j.power/1.85*100)+'%'}}/><i style={{width:(j.magic/1.85*100)+'%'}}/><i style={{width:(j.speed/1.42*100)+'%'}}/></div><small>攻撃　魔力　速度</small><b>この職業で始める</b></button>)}</div></div>}
  {hud.bannerTime>0&&<div className={'territory-banner '+currentOwner}><span>{hud.banner}</span><b>{current.name}</b></div>}
  <button className="map-toggle" onClick={()=>setMapOpen(v=>!v)}><Map size={16}/>世界地図 <kbd>M</kbd></button>
  <button className={'growth-toggle '+(hud.skillPoints?'ready':'')} onClick={()=>setGrowthOpen(v=>!v)}><Brain size={16}/>能力・スキル <b>{hud.skillPoints} SP</b></button>
  <button className="transfer-toggle" onClick={()=>setTransferOpen(v=>!v)}><RefreshCcw size={15}/>転職</button>
  {mapOpen&&<div className="world-map"><div className="panel-head"><div><Map size={18}/><b>魔界広域図</b></div><button onClick={()=>setMapOpen(false)}>×</button></div><div className="map-grid">{REGIONS.map(r=>{let seen=hud.discovered.includes(r.id),here=r.id===current.id,territory=ownerOf(hud,r);return <div key={r.id} className={'map-cell '+(seen?territory:'unknown')+(here?' here':'')}><span>{seen?r.biome:'未探索'}</span><b>{seen?r.name:'？？？'}</b>{here&&<i>現在地</i>}</div>})}</div><div className="map-legend"><span><i className="own"/>自領</span><span><i className="enemy"/>敵領</span><span><i className="wild"/>未支配</span><span><i className="unknown"/>未探索</span></div></div>}
  {rankOpen&&<div className="rank-panel"><div className="panel-head"><div><Shield size={18}/><b>魔族ランク</b></div><button onClick={()=>setRankOpen(false)}>×</button></div><div className="rank-track">{RANKS.map((r,i)=><span key={r} className={i===hud.rank?'current':i<hud.rank?'done':''}>{r}</span>)}</div><small>次の昇格条件</small><p>{hud.rank===7?'すべての条件を達成し、魔王に君臨している。':requirement(hud)}</p><div className="rank-stats"><span>敵撃破 {hud.kills}</span><span>強敵 {hud.bossKills}</span><span>領土 {hud.lands}</span><span>配下 {hud.minions}</span><span>拠点 Lv.{hud.base}</span><span>地域 {hud.discovered.length}/9</span></div><button className={'rank-up '+(ready?'ready':'')} onClick={rankUp}>{ready?'ランクアップ':'条件未達成'}</button><em>Lv.99だけでは魔王になれません</em></div>}
  {transferOpen&&currentJob&&<div className="transfer-panel"><div className="panel-head"><div><RefreshCcw size={18}/><b>転職の祭壇</b><span>世界進行は維持・職業進行は個別</span></div><button onClick={()=>setTransferOpen(false)}>×</button></div><div className="preserved"><ShieldCheck/><div><b>失われないもの</b><span>領土 {hud.lands}・配下 {hud.minions}・拠点 Lv.{hud.base}・実績 {hud.achievements}・重要所有物</span></div></div><div className="career-grid">{JOBS.map(j=>{let unlocked=jobUnlocked(hud,j),level=careerLevel(hud,j.id),active=j.id===hud.job,cost=3+Object.keys(hud.careers).length;return <button key={j.id} className={'career-card '+(active?'active ':'')+(unlocked?'':'locked ')+j.tier} disabled={active||!unlocked} onClick={()=>changeJob(j.id)} style={{'--job-color':j.color} as React.CSSProperties}><div><span>{j.tier==='advanced'?'上位・複合職':j.weapon}</span><b>{j.name}</b><small>{j.style}</small></div><strong>{active?'現在の職業':level?'保存 Lv.'+level:'新規 Lv.1'}</strong>{!unlocked&&<em><Lock/> {j.requires?.map(id=>JOBS.find(x=>x.id===id)?.name).join(' + ')}をLv.6</em>}{unlocked&&!active&&!level&&<em>代償：魔木・鉱石 各{cost}</em>}</button>})}</div><p className="transfer-warning">転職先ではLv.1・能力値・武器Lv.1から育成。以前の職業へ戻ると保存した進行を復元します。</p></div>}
  {growthOpen&&currentJob&&<div className="growth-panel"><div className="panel-head"><div><Brain size={18}/><b>成長ボード</b><span>{currentJob.name} / 職業Lv.{hud.lv}</span></div><button onClick={()=>setGrowthOpen(false)}>×</button></div><div className="growth-top"><div className="sp-wallet"><Sparkles/><span>使用可能スキルポイント</span><b>{hud.skillPoints}</b><small>レベルアップごとに3獲得</small></div><div className="weapon-card"><Swords/><div><span>職業専用武器</span><b>{currentJob.weapon} Lv.{hud.weaponLevel}</b></div><button onClick={upgradeWeapon}>強化</button></div></div><div className="growth-columns"><section><h3>能力値</h3><div className="stat-list">{STAT_INFO.map(s=><div className="stat-row" key={s.id}><div><b>{s.name}</b><small>{s.desc}</small></div><strong>{hud.stats[s.id]}</strong><button disabled={!hud.skillPoints} onClick={()=>allocate(s.id)} aria-label={s.name+'を強化'}><Plus/></button></div>)}</div></section><section><h3>{currentJob.name} 基礎スキルツリー</h3><div className="skill-tree">{currentJob.skills.map((s,i)=>{let learned=hud.unlocked.includes(s.id),available=hud.lv>=s.level&&hud.skillPoints>=s.cost;return <button key={s.id} className={(learned?'learned ':'')+(available?'available':'')} onClick={()=>learn(s)}><i>{learned?<Sparkles/>:<Lock/>}</i><div><span>段階 {i+1}　Lv.{s.level}</span><b>{s.name}</b><small>{s.desc}</small></div><em>{learned?'習得済':s.cost+' SP'}</em></button>})}</div><div className="job-doctrine"><b>戦闘スタイル</b><p>{currentJob.style}</p><span>威力 ×{currentJob.power.toFixed(2)}　間合い ×{currentJob.range.toFixed(2)}　速度 ×{currentJob.speed.toFixed(2)}</span></div></section></div><section className="milestones"><h3>レベル節目 — 二択スキル</h3><p>最初の1つは無料選択。選ばなかった候補も後からSPで習得できます。</p>{milestoneGroups.map(group=><div className={'milestone-group '+(hud.lv>=group.level?'open':'locked')} key={group.level}><strong>Lv.{group.level}</strong><div>{group.skills.map(skill=>{let learned=hud.unlocked.includes(skill.id),chosen=group.skills.some(s=>hud.unlocked.includes(s.id));return <button key={skill.id} disabled={learned||hud.lv<group.level} className={learned?'learned':''} onClick={()=>learnMilestone(group,skill)}><span>{learned?'習得済':chosen?skill.cost+' SP':'無料選択'}</span><b>{skill.name}</b><small>{skill.desc}</small></button>})}</div></div>)}</section></div>}
  <div className="quest-card"><span>現在地</span><b>{current.landmark}</b><small>{current.biome} / {currentOwner==='enemy'?'敵勢力が支配中':currentOwner==='own'?'あなたの支配地':'まだ誰の領土でもない'}</small></div>
  <div className="notice">{hud.message}</div><div className="combat-controls"><button className="action attack" onClick={attack}><Swords/><span>通常攻撃</span><kbd>SPACE</kbd></button><button className="action heavy" onClick={heavyAttack}><Hammer/><span>強攻撃</span><kbd>Q</kbd></button><button className={'action guard '+(hud.guarding?'active':'')} onPointerDown={()=>{game.current.guarding=true;sync()}} onPointerUp={()=>{game.current.guarding=false;sync()}} onPointerLeave={()=>{game.current.guarding=false}}><Shield/><span>防御</span><kbd>R 長押し</kbd></button><button className="action evade" onClick={dodge}><Wind/><span>回避</span><kbd>SHIFT</kbd></button><button className="action combat-skill" onClick={useCombatSkill}><Zap/><span>スキル</span><kbd>C</kbd></button></div><div className="utility-controls"><button onClick={recruit}><Users/>配下 <kbd>E</kbd></button><button onClick={gather}><Sparkles/>採集 <kbd>F</kbd></button><button onClick={build}><Hammer/>建築</button><button onClick={raid}><Skull/>領土戦</button></div>
  <div className="resources"><span>魔木 <b>{hud.wood}</b></span><span>瘴気鉱 <b>{hud.ore}</b></span></div><div className="joystick" onPointerDown={e=>{(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);stick.current.on=true}} onPointerMove={e=>{if(!stick.current.on)return;let r=e.currentTarget.getBoundingClientRect();stick.current.x=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/(r.width/2)));stick.current.y=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/(r.height/2)))}} onPointerUp={()=>stick.current={x:0,y:0,on:false}}><i/></div>
  <div className="hint"><Binoculars size={14}/>リアルタイム戦闘：攻撃・強攻撃・防御・回避・スキルを使い分ける</div>
 </section><section className="legend"><div><b>自由探索</b><span>9地域を境界なしで移動</span></div><div><b>領土侵入</b><span>敵領土へ自由に入り、支配者を呼び出す</span></div><div><b>条件制ランク</b><span>レベル・領土・配下・実績を揃えて昇格</span></div></section></main>
}
