'use client';
import {useEffect,useRef,useState} from 'react';
import {Flame,Hammer,Heart,Shield,Skull,Sparkles,Swords,Users} from 'lucide-react';
type Mob={id:number;x:number;y:number;hp:number;max:number;name:string;boss?:boolean;ally?:boolean};
type World={x:number;y:number;hp:number;maxHp:number;xp:number;lv:number;wood:number;gem:number;minions:number;base:number;land:number;msg:string;mobs:Mob[];nodes:{x:number;y:number;wood:boolean;n:number}[];cd:number};
const make=():World=>({x:225,y:390,hp:100,maxHp:100,xp:0,lv:1,wood:0,gem:0,minions:0,base:1,land:0,msg:'最弱の魔族よ、魔王への一歩を踏み出せ。',cd:0,mobs:[{id:1,x:410,y:350,hp:30,max:30,name:'はぐれインプ'},{id:2,x:520,y:265,hp:36,max:36,name:'灰角インプ'},{id:3,x:655,y:430,hp:44,max:44,name:'溶岩ハウンド'},{id:4,x:760,y:235,hp:48,max:48,name:'火噛みハウンド'}],nodes:[{x:280,y:190,wood:false,n:5},{x:335,y:520,wood:true,n:5},{x:590,y:175,wood:false,n:5},{x:825,y:510,wood:true,n:5}]});
const dis=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),w=useRef(make()),keys=useRef<Record<string,boolean>>({}),stick=useRef({x:0,y:0,on:false}),[hud,setHud]=useState(w.current);
 const sync=()=>setHud({...w.current,mobs:[...w.current.mobs],nodes:[...w.current.nodes]});
 const msg=(s:string)=>{w.current.msg=s;sync()};
 const grow=(n:number)=>{let a=w.current;a.xp+=n;let need=a.lv*36;if(a.xp>=need){a.xp-=need;a.lv++;a.maxHp+=18;a.hp=a.maxHp;a.msg='進化！ Lv.'+a.lv+'になった。';}};
 const attack=()=>{let a=w.current;if(a.cd>0)return;let t=a.mobs.filter(m=>!m.ally&&dis(a,m)<108).sort((p,q)=>dis(a,p)-dis(a,q))[0];if(!t)return msg('敵に近づいて攻撃しよう。');let d=14+a.lv*7+a.minions*2;t.hp-=d;a.cd=.3;if(t.hp<=0){if(t.boss){a.land=1;a.wood+=8;a.gem+=8;a.mobs=a.mobs.filter(m=>m!==t);a.msg='領土ボスを討伐！ 黒曜領を奪取した。'}else{a.mobs=a.mobs.filter(m=>m!==t);a.gem++;grow(18);a.msg=t.name+'を撃破。瘴気結晶を得た。'}}else a.msg=t.name+'に '+d+' ダメージ！ 半分まで削れば配下にできる。';sync()};
 const recruit=()=>{let a=w.current,t=a.mobs.filter(m=>!m.ally&&!m.boss&&m.hp/m.max<=.5&&dis(a,m)<120)[0];if(!t)return msg('HP半分以下の敵に近づいて配下にしよう。');t.ally=true;t.hp=t.max;a.minions++;grow(10);a.msg=t.name+'が忠誠を誓った！ 配下 +1。';sync()};
 const gather=()=>{let a=w.current,n=a.nodes.filter(n=>n.n&&dis(a,n)<85)[0];if(!n)return msg('資源のそばへ移動しよう。紫は結晶、橙は魔木。');n.n--;if(n.wood)a.wood++;else a.gem++;a.msg=n.wood?'魔木を回収した。':'瘴気結晶を回収した。';sync()};
 const build=()=>{let a=w.current,c=2+a.base;if(a.wood<c||a.gem<c)return msg('拠点強化には魔木・結晶 各'+c+'が必要。');a.wood-=c;a.gem-=c;a.base++;a.maxHp+=12;a.hp=a.maxHp;a.msg='拠点をLv.'+a.base+'に拡張！';sync()};
 const raid=()=>{let a=w.current;if(a.land)return msg('黒曜領はすでにあなたの領土だ。');if(a.lv<3||a.base<2||a.minions<1)return msg('襲撃条件：Lv.3 / 拠点Lv.2 / 配下1体。');if(!a.mobs.some(m=>m.boss)){a.mobs.push({id:99,x:900,y:310,hp:210,max:210,name:'黒曜将軍ヴァルガ',boss:true});a.msg='黒曜領へ侵入！ 黒曜将軍ヴァルガが現れた。';sync()}};
 useEffect(()=>{let d=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;if(e.key===' '){e.preventDefault();attack()}if(e.key==='e')recruit();if(e.key==='f')gather()},u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[]);
 useEffect(()=>{let c=canvas.current;if(!c)return;let g=c.getContext('2d')!,f=0,last=performance.now(),id=0,fit=()=>{let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);c.width=r.width*d;c.height=r.height*d;g.setTransform(d,0,0,d,0,0)};fit();let ob=new ResizeObserver(fit);ob.observe(c);let bar=(x:number,y:number,p:number,col:string,z=42)=>{g.fillStyle='#12081acc';g.fillRect(x-z/2,y,z,5);g.fillStyle=col;g.fillRect(x-z/2+1,y+1,(z-2)*Math.max(0,p),3)};let drawMob=(m:Mob)=>{let b=Math.sin(f/15+m.id)*2;g.save();g.translate(m.x,m.y+b);g.fillStyle='#0008';g.beginPath();g.ellipse(0,15,m.boss?36:18,7,0,0,7);g.fill();g.fillStyle=m.ally?'#4fe6ba':m.boss?'#f33364':'#b264e7';g.beginPath();g.arc(0,m.boss?-12:-2,m.boss?22:15,0,7);g.fill();g.fillStyle='#2a103a';g.beginPath();g.moveTo(-11,-9);g.lineTo(-15,-27);g.lineTo(-2,-15);g.moveTo(11,-9);g.lineTo(15,-27);g.lineTo(2,-15);g.fill();g.restore();bar(m.x,m.y-(m.boss?63:31),m.hp/m.max,m.ally?'#54e9c3':'#ff5879',m.boss?82:38);g.fillStyle='#ffe4c8';g.font='10px system-ui';g.textAlign='center';g.fillText(m.ally?'配下':m.name,m.x,m.y+28)};
 let loop=(now:number)=>{let dt=Math.min(.04,(now-last)/1000);last=now;f++;let a=w.current,ax=(keys.current.d||keys.current.arrowright?1:0)-(keys.current.a||keys.current.arrowleft?1:0)+(stick.current.on?stick.current.x:0),ay=(keys.current.s||keys.current.arrowdown?1:0)-(keys.current.w||keys.current.arrowup?1:0)+(stick.current.on?stick.current.y:0),z=Math.hypot(ax,ay)||1;a.x=Math.max(55,Math.min(1010,a.x+ax/z*155*dt));a.y=Math.max(90,Math.min(600,a.y+ay/z*155*dt));a.cd=Math.max(0,a.cd-dt);a.mobs.forEach(m=>{let d=dis(a,m);if(m.ally){if(d>70){m.x+=(a.x-m.x)/d*60*dt;m.y+=(a.y-m.y)/d*60*dt}}else{if(d<180&&d>46){m.x+=(a.x-m.x)/d*32*dt;m.y+=(a.y-m.y)/d*32*dt}if(d<44&&f%55===0){a.hp-=m.boss?12:4;a.msg=m.name+'の攻撃！'}}});if(a.hp<=0){a.x=225;a.y=390;a.hp=a.maxHp;a.msg='拠点に帰還した。もう一度挑もう。'}let cw=c.clientWidth,ch=c.clientHeight;g.clearRect(0,0,cw,ch);g.save();g.scale(cw/1060,ch/680);let bg=g.createLinearGradient(0,0,0,680);bg.addColorStop(0,'#170d2a');bg.addColorStop(.55,'#3c1935');bg.addColorStop(1,'#150b1d');g.fillStyle=bg;g.fillRect(0,0,1060,680);for(let i=0;i<38;i++){let x=(i*83+41)%1060,y=(i*137+80)%680;g.fillStyle=i%3?'#6c346b2e':'#fa5a341f';g.beginPath();g.ellipse(x,y,56+i%4*13,20+i%3*12,.2,0,7);g.fill()}g.strokeStyle='#ff6d472e';g.lineWidth=7;g.beginPath();g.moveTo(0,615);g.bezierCurveTo(250,530,350,680,570,560);g.bezierCurveTo(770,450,860,590,1060,500);g.stroke();g.fillStyle='#241630';g.fillRect(125,330,170,150);g.fillStyle='#55345e';g.beginPath();g.moveTo(110,335);g.lineTo(210,250);g.lineTo(310,335);g.fill();g.fillStyle='#ff8751';g.fillRect(185,385,44,70);g.fillStyle='#f8c06e';g.font='bold 12px system-ui';g.textAlign='center';g.fillText('小さな拠点 Lv.'+a.base,210,505);a.nodes.forEach(n=>{if(!n.n)return;g.save();g.translate(n.x,n.y);g.fillStyle=n.wood?'#db873e':'#bd7cff';g.beginPath();g.moveTo(0,-28);g.lineTo(17,8);g.lineTo(-17,8);g.fill();g.restore();g.fillStyle='#f8d9d0';g.font='10px system-ui';g.fillText((n.wood?'魔木 ×':'結晶 ×')+n.n,n.x,n.y+27)});a.mobs.forEach(drawMob);g.save();g.translate(a.x,a.y+Math.sin(f/8)*2);g.fillStyle='#0008';g.beginPath();g.ellipse(0,17,18,7,0,0,7);g.fill();g.fillStyle='#6eecad';g.beginPath();g.arc(0,-2,15,0,7);g.fill();g.fillStyle='#372052';g.beginPath();g.moveTo(-11,-8);g.lineTo(-15,-27);g.lineTo(-2,-15);g.moveTo(11,-8);g.lineTo(15,-27);g.lineTo(2,-15);g.fill();g.restore();bar(a.x,a.y-37,a.hp/a.maxHp,'#65ebb4',48);g.fillStyle='#eaffd8';g.font='bold 11px system-ui';g.fillText('あなた',a.x,a.y+33);g.restore();if(f%12===0)sync();id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(id);ob.disconnect()}},[]);
 let need=hud.lv*36,rank=hud.lv>=4?'B':hud.lv>=3?'C':'F',next=hud.land?'黒曜領を手に入れた。魔王への礎が完成！':hud.lv<3?'敵を倒し、Lv.3を目指す':hud.minions<1?'弱った敵を配下にする':hud.base<2?'資源で拠点を強化する':'黒曜領へ襲撃する';
 return <main className="game-shell"><section className="game-frame"><div className="world-art"/><header className="topbar"><div className="brand"><Flame size={20} fill="currentColor"/><span>魔界成り上がり譚</span><small>RISE OF THE WEAKEST</small></div><div className="objective"><Sparkles size={15}/>{hud.land?'黒曜領を支配中 — 魔王への進軍':'目標：弱者から魔王へ'}</div><button className="reset" onClick={()=>{w.current=make();sync()}}>最初から</button></header><div className="hud-left"><div className="rank-badge"><span>RANK</span><b>{rank}</b></div><div className="vitals"><div className="lv">LV <b>{hud.lv}</b></div><div className="meter hp"><i style={{width:(hud.hp/hud.maxHp*100)+'%'}}/></div><div className="meter xp"><i style={{width:(hud.xp/need*100)+'%'}}/></div><small>HP {Math.ceil(hud.hp)}/{hud.maxHp}　EXP {hud.xp}/{need}</small></div></div><div className="hud-right"><div><Users size={16}/>配下 <b>{hud.minions}</b></div><div><Hammer size={16}/>拠点 <b>Lv.{hud.base}</b></div><div><Shield size={16}/>領土 <b>{hud.land}/1</b></div></div><canvas ref={canvas} className="game-canvas"/><div className="quest-card"><span>次の一手</span><b>{next}</b></div><div className="notice">{hud.msg}</div><div className="controls"><button className="action attack" onClick={attack}><Swords/><span>攻撃</span><kbd>SPACE</kbd></button><button className="action recruit" onClick={recruit}><Users/><span>配下にする</span><kbd>E</kbd></button><button className="action gather" onClick={gather}><Sparkles/><span>採集</span><kbd>F</kbd></button><button className="action build" onClick={build}><Hammer/><span>建築</span></button><button className="action raid" onClick={raid}><Skull/><span>領土襲撃</span></button></div><div className="resources"><span>魔木 <b>{hud.wood}</b></span><span>結晶 <b>{hud.gem}</b></span></div><div className="joystick" onPointerDown={e=>{(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);stick.current.on=true}} onPointerMove={e=>{if(!stick.current.on)return;let r=e.currentTarget.getBoundingClientRect();stick.current.x=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/(r.width/2)));stick.current.y=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/(r.height/2)))}} onPointerUp={()=>stick.current={x:0,y:0,on:false}}><i/></div><div className="hint"><Heart size={14}/>移動：WASD / 矢印キー / 左スティック　攻撃：Space</div></section><section className="legend"><div><b>探索</b><span>紫の結晶・橙の魔木を探す</span></div><div><b>戦闘と配下</b><span>HP半分以下の敵は仲間にできる</span></div><div><b>建国</b><span>資源を投じて拠点を拡張し、領土ボスに挑む</span></div></section></main>
}
